# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0004_auto_20160917_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(default='0:00', max_length=255, verbose_name=b'Dauer des Videos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name=b'Videotitel auf YouTube'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='uploader',
            field=models.CharField(default='', max_length=255, verbose_name=b'Uploader auf YouTube'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jukebox.JukeboxUser'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jukebox.JukeboxUser'),
        ),
        migrations.AlterField(
            model_name='room',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jukebox.JukeboxUser'),
        ),
        migrations.AlterField(
            model_name='usertoroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jukebox.JukeboxUser'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jukebox.JukeboxUser'),
        ),
    ]
