# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jukebox.models


class Migration(migrations.Migration):

    dependencies = [
        ('jukebox', '0009_auto_20160917_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jukeboxuser',
            name='room_id',
        ),
        migrations.AddField(
            model_name='video',
            name='thumb_url',
            field=models.URLField(default='', max_length=255, verbose_name=b'YouTube Thumbnail URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jukebox.JukeboxUser'),
        ),
        migrations.AlterField(
            model_name='jukeboxuser',
            name='name',
            field=models.CharField(default=jukebox.models.get_random_sessionid, max_length=255),
        ),
        migrations.AlterField(
            model_name='jukeboxuser',
            name='session_id',
            field=models.CharField(default=jukebox.models.get_random_sessionid, max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jukebox.JukeboxUser'),
        ),
        migrations.AlterField(
            model_name='room',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jukebox.JukeboxUser'),
        ),
        migrations.AlterField(
            model_name='usertoroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jukebox.JukeboxUser'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jukebox.JukeboxUser'),
        ),
    ]
